#!/usr/bin/env node
/**
 * Emits data-report.txt: an audit of every empty verse slot in the bundled
 * texts (P1-4). The three bundles share the source corpus's aligned verse
 * grid; slots the grid leaves empty in a translation are skipped in display.
 * This report lists all of them so printed editions can be checked.
 *
 * Runs standalone (npm run report) and at the end of npm run data.
 * Output is deterministic — no timestamps — so CI can diff it.
 */
import { realpathSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const TRANSLATIONS = ["drc", "cpdv", "vulgate"];

/**
 * Hand-verified audit notes for scattered slots (checked against printed
 * editions / cross-bundle text during the P1-4 review). Most empty slots are
 * pure renumbering — the verse's words sit in a neighbouring slot — but these
 * are corpus defects: the printed verse is misfiled and another is absent.
 */
const VERIFIED_NOTES = {
  "1-kings 17:19":
    "drc defect: printed Douay 3 Kings 17:19 sits at grid 17:11; printed 17:11 (“…a morsel of bread”) is absent from the bundle",
  "proverbs 30:29":
    "drc defect: printed Douay 30:29 sits at grid 30:19; printed 30:19 (“the way of an eagle…”) is absent from the bundle",
  "baruch 6:37":
    "drc defect: printed Douay 6:37 sits at grid 6:7; printed 6:7 (the craftsman-polished tongue) is absent from the bundle"
};

async function loadBundles(root) {
  const bundles = {}; // translation -> { order: slug[], books: { slug -> chapters[][] } }
  for (const t of TRANSLATIONS) {
    const dir = join(root, "public", "data", t);
    const idx = JSON.parse(await readFile(join(dir, "index.json"), "utf8"));
    const books = {};
    for (const slug of idx.books) {
      books[slug] = JSON.parse(await readFile(join(dir, `${slug}.json`), "utf8")).chapters;
    }
    bundles[t] = { order: idx.books, books };
  }
  return bundles;
}

/** Slugs in drc order, then any extras from the other bundles. */
function bookOrder(bundles) {
  const order = [...bundles.drc.order];
  const seen = new Set(order);
  for (const t of TRANSLATIONS) {
    for (const slug of bundles[t].order) {
      if (!seen.has(slug)) {
        seen.add(slug);
        order.push(slug);
      }
    }
  }
  return order;
}

export async function buildReport(root) {
  const bundles = await loadBundles(root);
  const order = bookOrder(bundles);
  const empty = (s) => !s || !s.trim();

  // Per-translation totals.
  const totals = {}; // t -> { books, verses, withText, empty }
  for (const t of TRANSLATIONS) {
    const sum = { books: 0, verses: 0, withText: 0, empty: 0 };
    for (const slug of bundles[t].order) {
      sum.books++;
      for (const ch of bundles[t].books[slug]) {
        for (const v of ch) {
          sum.verses++;
          if (empty(v)) sum.empty++;
          else sum.withText++;
        }
      }
    }
    totals[t] = sum;
  }

  // Books whose every slot is empty in every bundle (source-corpus placeholders).
  const placeholders = [];
  for (const slug of order) {
    const allEmpty = TRANSLATIONS.every((t) =>
      (bundles[t].books[slug] ?? []).every((ch) => ch.every(empty))
    );
    if (allEmpty) {
      const chapters = bundles.drc.books[slug] ?? [];
      placeholders.push({
        slug,
        chapters: chapters.length,
        slots: chapters.reduce((a, ch) => a + ch.length, 0),
        shape: chapters.map((ch) => ch.length)
      });
    }
  }
  const placeholderSet = new Set(placeholders.map((p) => p.slug));

  // Every empty slot outside the placeholder books, grouped per slot.
  const scattered = []; // { slug, ch, v, emptyIn: t[], sample?, prevTail? }
  for (const slug of order) {
    if (placeholderSet.has(slug)) continue;
    const grid = bundles.drc.books[slug] ?? bundles.cpdv.books[slug] ?? bundles.vulgate.books[slug];
    grid.forEach((chap, ci) => {
      chap.forEach((_, vi) => {
        const emptyIn = TRANSLATIONS.filter((t) => empty(bundles[t].books[slug]?.[ci]?.[vi]));
        if (!emptyIn.length) return;
        const withText = TRANSLATIONS.find((t) => !empty(bundles[t].books[slug]?.[ci]?.[vi]));
        const entry = { slug, ch: ci + 1, v: vi + 1, emptyIn };
        if (withText) {
          entry.sample = `${withText}: "${bundles[withText].books[slug][ci][vi].slice(0, 60)}…"`;
        } else {
          const prev = bundles.drc.books[slug]?.[ci]?.[vi - 1] ?? "";
          entry.sample = `drc ${ci + 1}:${vi} ends: "…${prev.slice(-50)}"`;
        }
        scattered.push(entry);
      });
    });
  }

  const lines = [];
  const w = (s = "") => lines.push(s);

  w("Fidelis bundled-text report");
  w("Generated by scripts/build-report.mjs from public/data/ — do not hand-edit.");
  w("Regenerate: npm run report (also runs at the end of npm run data).");
  w();
  w("The three bundles share the source corpus's aligned verse grid: every");
  w("translation has the identical chapter/verse shape. Where the grid leaves a");
  w("slot empty in a translation, the app skips it in display (never a bare");
  w("verse number). This file lists every empty slot so the bundles can be");
  w("checked against printed editions.");
  w();
  w("== Summary ==");
  w("translation  books  verses  with-text  empty");
  for (const t of TRANSLATIONS) {
    const s = totals[t];
    w(
      `${t.padEnd(12)} ${String(s.books).padStart(5)} ${String(s.verses).padStart(7)} ` +
        `${String(s.withText).padStart(10)} ${String(s.empty).padStart(6)}`
    );
  }
  w();
  w("== Appendix placeholders (no text in any bundle) ==");
  w("The source corpus lists these books but carries no text for them in any");
  w("translation; every slot below is empty in drc, cpdv, and vulgate alike.");
  w("The app keeps them in the book picker, marked outside the canon, and the");
  w("Reader states that the bundled source does not include the text.");
  w();
  for (const p of placeholders) {
    w(
      `${p.slug.padEnd(20)} ${String(p.chapters).padStart(2)} chapter(s), ` +
        `${String(p.slots).padStart(4)} slots  [${p.shape.join(", ")}]`
    );
  }
  w(
    `total: ${placeholders.reduce((a, p) => a + p.chapters, 0)} chapters, ` +
      `${placeholders.reduce((a, p) => a + p.slots, 0)} slots per translation`
  );
  w();
  w("== Scattered empty slots (versification drift and corpus defects) ==");
  w("Each line is one grid slot empty in at least one translation outside the");
  w("placeholder books. Where another bundle carries text in the same slot, its");
  w("opening words are shown. In most such cases the empty bundle packs that");
  w("verse's words into a neighbouring verse and only the numbering drifts from");
  w("printed editions (e.g. the printed Douay 1 Thessalonians 4:18 sits in the");
  w("grid at 4:17) — but not all: slots annotated “defect” below are verified");
  w("cases where the printed verse is misfiled and another verse is absent from");
  w("the bundle outright. Where the slot is empty in every bundle, the tail of");
  w("the preceding verse is shown; the grid simply over-counts that chapter.");
  w("Check unannotated lines against hard copies before relying on them.");
  w();
  for (const s of scattered) {
    const ref = `${s.slug} ${s.ch}:${s.v}`;
    w(`${ref.padEnd(22)} empty in ${s.emptyIn.join(", ").padEnd(20)} ${s.sample}`);
    const note = VERIFIED_NOTES[ref];
    if (note) w(`    note: ${note}`);
  }
  w();
  w(`scattered slots: ${scattered.length}`);
  for (const t of TRANSLATIONS) {
    w(`  empty in ${t}: ${scattered.filter((s) => s.emptyIn.includes(t)).length} scattered + ` +
        `${placeholders.reduce((a, p) => a + p.slots, 0)} placeholder = ${totals[t].empty} total`);
  }
  w();

  return lines.join("\n");
}

export async function writeReport(root) {
  const r = root ?? join(dirname(fileURLToPath(import.meta.url)), "..");
  const text = await buildReport(r);
  const out = join(r, "data-report.txt");
  await writeFile(out, text);
  console.log(`Wrote ${out}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(realpathSync(process.argv[1])).href) {
  await writeReport();
}
